language: node_js
node_js:
  - "6.0"
addons:
  apt:
    packages:
      - libcairo2-dev
      - libjpeg-dev
      - libpango1.0-dev
      - libgif-dev
      - build-essential
      - g++
script:
  - npm run lint
  - npm test
